name: actions workflow

on:
  push:  
    branches: [ master ]

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: js-hello-action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Prasanth Padmalayam'
      - name: 2nd step
        run: echo "Log time - ${{ steps.greet.outputs.time }}"
