name: shell script workflow
on:
  push:
    branches: [master]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest 
    steps: 
        - name: echo a string
          run: echo " Hello world1"
        - name: echo multiline script
          run: | 
            node -v
            npm -v
        - name: python commands
          shell: python
          run: |
            import platform
            print(platform.processor())
  
  run-series-command:
    runs-on: ubuntu-18.04
    needs: ["run-shell-command"]
    steps:
        - name: series steps
          run: echo "series - hello world"
          